import type { Certs } from "./columns"

// Certificates in chronological order by date_completed (earliest first). IDs match order.
export const certs: Certs[] = [
  { id: "1", category: "Game Development", specialisation: "Game Development & Interactive Systems", course: "Complete C# Unity Game Developer 2D", details: "", provider: "Udemy", date_completed: new Date("2025-01-18"), link: "https://www.udemy.com/certificate/UC-e0c6cc40-fe55-4c12-b4a0-247b7b9b5966/", status: "Completed" },
  { id: "2", category: "Programming Languages", specialisation: "JavaScript", course: "Learn JavaScript Course", details: "", provider: "Codecademy", date_completed: new Date("2025-03-06"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/705dcb15de0da4dd9d9fc4f3274b430e", status: "Completed" },
  { id: "3", category: "Frontend Development", specialisation: "HTML & CSS", course: "Learn HTML Course", details: "", provider: "Codecademy", date_completed: new Date("2025-05-08"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/9eb0741e5ebef1f9f58a53bfac67d3a7", status: "Completed" },
  { id: "4", category: "Frontend Development", specialisation: "HTML & CSS", course: "Learn CSS Course", details: "", provider: "Codecademy", date_completed: new Date("2025-05-01"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/9a5bb1fc45b4281af1fffec93b0aaf05", status: "Completed" },
  { id: "5", category: "Frontend Development", specialisation: "JavaScript", course: "Building Interactive JavaScript Websites Course", details: "", provider: "Codecademy", date_completed: new Date("2025-06-18"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/36ae898a1d1c8524815305b2d1d2ebab", status: "Completed" },
  { id: "6", category: "Other Technical Training", specialisation: "Computer Science & Systems", course: "Computer Science 101: Master the Theory Behind Programming", details: "", provider: "Udemy", date_completed: new Date("2025-06-21"), link: "https://www.udemy.com/certificate/UC-f1262c2e-17fd-4bd0-9653-3213a632b286/", status: "Completed" },
  { id: "7", category: "Frontend Development", specialisation: "React Ecosystem", course: "Learn React Course", details: "", provider: "Codecademy", date_completed: new Date("2025-06-14"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/af00e5032d0a68cc84879983f5d8333b", status: "Completed" },
  { id: "8", category: "Other Technical Training", specialisation: "Tooling & Development Workflow", course: "Learn Git & GitHub Course", details: "", provider: "Codecademy", date_completed: new Date("2025-06-18"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/a8ab218d5950c29861635cc0bf12fd13", status: "Completed" },
  { id: "9", category: "Programming Languages", specialisation: "Python", course: "Learn Python 3 Course", details: "", provider: "Codecademy", date_completed: new Date("2025-08-01"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/6c152bd262967f8c941c9707ed636bda", status: "Completed" },
  { id: "10", category: "Programming Languages", specialisation: "TypeScript", course: "Learn TypeScript Course", details: "", provider: "Codecademy", date_completed: new Date("2025-09-05"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/56fb1e71303e37b643bb1905f31c8a09", status: "Completed" },
  { id: "11", category: "Frontend Development", specialisation: "React Ecosystem", course: "Learn Redux Course", details: "", provider: "Codecademy", date_completed: new Date("2025-09-28"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/7bec2ab40c4dcf741cd2ff8d50a35e2d", status: "Completed" },
  { id: "12", category: "Other Technical Training", specialisation: "Tooling & Development Workflow", course: "Learn the Command Line Course", details: "", provider: "Codecademy", date_completed: new Date("2025-10-04"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/c87ba0541f8be78bc2f4ba1128233f6f", status: "Completed" },
  { id: "13", category: "Other Technical Training", specialisation: "Computer Science & Systems", course: "Learn Raspberry Pi Course", details: "", provider: "Codecademy", date_completed: new Date("2025-10-13"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/f6a7750cc41a463cacb30185ea8e5c7c", status: "Completed" },
  { id: "14", category: "Frontend Development", specialisation: "HTML & CSS", course: "Learn Sass Course", details: "", provider: "Codecademy", date_completed: new Date("2025-10-26"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/eb1ffda40f347629dcef6de33d3f9741", status: "Completed" },
  { id: "15", category: "Frontend Development", specialisation: "React Ecosystem", course: "Create a Front-End App with React [Skill Path]", details: "", provider: "Codecademy", date_completed: new Date("2025-10-26"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/5c9ce0b45f1de879ebcad4fd", status: "Completed" },
  { id: "16", category: "Backend & Databases", specialisation: "Node & Express", course: "Learn Node.js Course", details: "", provider: "Codecademy", date_completed: new Date("2025-12-07"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/240305d50b925c17868f1ac7a21a3261", status: "Completed" },
  { id: "17", category: "Backend & Databases", specialisation: "Node & Express", course: "Learn Express Course", details: "", provider: "Codecademy", date_completed: new Date("2025-12-08"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/85396dd6e2e850ab34e904243aa464c6", status: "Completed" },
  { id: "18", category: "Backend & Databases", specialisation: "Databases & SQL", course: "Learn SQL Course", details: "", provider: "Codecademy", date_completed: new Date("2025-12-13"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/042a4e5884e3eb6ea1f2a12be6abb851", status: "Completed" },
  { id: "19", category: "Backend & Databases", specialisation: "Databases & SQL", course: "Learn Node-SQLite Course", details: "", provider: "Codecademy", date_completed: new Date("2025-12-16"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/f0257b235b081aca2766010aad2df800", status: "Completed" },
  { id: "20", category: "Backend & Databases", specialisation: "Node & Express", course: "Create a Back-End App with JavaScript [Skill Path]", details: "", provider: "Codecademy", date_completed: new Date("2026-01-26"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/5cb678013709022f5b908913", status: "Completed" },
  { id: "21", category: "Backend & Databases", specialisation: "Databases & SQL", course: "Design Databases With PostgreSQL Skill Path", details: "", provider: "Codecademy", date_completed: new Date("2026-01-09"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/5f64e3b492de0000131ecbe0", status: "Completed" },
  { id: "22", category: "Backend & Databases", specialisation: "Node & Express", course: "Securing Express Applications [Skill Path]", details: "", provider: "Codecademy", date_completed: new Date("2026-01-30"), link: "https://www.codecademy.com/profiles/LordMarshy/certificates/61427ba3ae2b35001106e73c", status: "Completed" },

  { id: "23", category: "Dummy", specialisation: "Dummy", course: "Dummy", details: "", provider: "Codecademy", date_completed: new Date("2026-02-01"), link: "", status: "Completed" },
  { id: "24", category: "Dummy", specialisation: "Dummy", course: "Dummy", details: "", provider: "Codecademy", date_completed: new Date("2026-02-02"), link: "", status: "Completed" },
  { id: "25", category: "Dummy", specialisation: "Dummy", course: "Dummy", details: "", provider: "Codecademy", date_completed: new Date("2026-02-03"), link: "", status: "Completed" },
  { id: "26", category: "Dummy", specialisation: "Dummy", course: "Dummy", details: "", provider: "Codecademy", date_completed: new Date("2026-02-04"), link: "", status: "Completed" },
]

export default certs;